services:
  app:
    container_name: app_${APP_NAME}
    build:
      context: .
      target: dev
      dockerfile: ./docker/app/Dockerfile
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres
      - valkey

  postgres:
    container_name: postgres_${APP_NAME}
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    container_name: valkey_${APP_NAME}
    image: valkey/valkey:9.0-alpine3.22
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped
    command: valkey-server --appendonly yes

volumes:
  app_data:
  valkey_data:
  postgres_data:
