version: "3"

dotenv: [".env"]

tasks:
  setup:
    desc: "Setup project"
    deps: [migrate-up]

  migrate-up:
    desc: "Run migrations"
    cmds:
      - migrate -path ./migrations -database "$POSTGRES_URL" up

  migrate-down:
    desc: "Rollback migrations"
    cmds:
      - migrate -path ./migrations -database "$POSTGRES_URL" down -all

  lint-run:
    desc: "Fix code"
    cmds:
      - golangci-lint run --config .golangci.yml --fix

  swag-init:
    desc: "Generate docs"
    cmds:
      - swag init -g cmd/http/main.go
