definitions:
  request.CreateUrl:
    properties:
      long_url:
        maxLength: 2048
        type: string
    required:
    - long_url
    type: object
  response.Error:
    properties:
      error:
        type: string
      errors:
        items:
          type: string
        type: array
    type: object
  response.Url:
    properties:
      long_url:
        type: string
      short_code:
        type: string
    type: object
  response.UrlStats:
    properties:
      clicks_count:
        type: integer
      created_at:
        type: integer
      id:
        type: integer
      long_url:
        type: string
      short_code:
        type: string
      updated_at:
        type: integer
    type: object
info:
  contact: {}
paths:
  /{short_code}:
    get:
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: click short code
      tags:
      - url
  /urls:
    post:
      consumes:
      - application/json
      parameters:
      - description: create url
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.CreateUrl'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Url'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: create url
      tags:
      - url
  /urls/{short_code}:
    get:
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UrlStats'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: url stats
      tags:
      - url
swagger: "2.0"
