basePath: /
definitions:
  model.URL:
    properties:
      created_at:
        type: string
      id:
        type: integer
      original_url:
        type: string
      short_code:
        type: string
      updated_at:
        type: string
    type: object
  request.CreateURL:
    properties:
      original_url:
        type: string
    required:
    - original_url
    type: object
  response.Fail:
    properties:
      error:
        type: string
      errors:
        items:
          type: string
        type: array
    type: object
  response.Ok:
    properties:
      data: {}
    type: object
info:
  contact: {}
  title: url shortener api
  version: "1.0"
paths:
  /{short_code}:
    get:
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: redirect to url
      tags:
      - url
  /urls:
    post:
      consumes:
      - application/json
      parameters:
      - description: create url
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.CreateURL'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.Ok'
            - properties:
                data:
                  $ref: '#/definitions/model.URL'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: create url
      tags:
      - url
swagger: "2.0"
