basePath: /
definitions:
  dto.Pagination:
    properties:
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  model.Click:
    properties:
      created_at:
        type: string
      id:
        type: integer
      ip:
        type: string
      url_id:
        type: integer
      user_agent:
        type: string
    type: object
  model.Url:
    properties:
      created_at:
        type: string
      id:
        type: integer
      long_url:
        type: string
      short_code:
        type: string
      updated_at:
        type: string
    type: object
  model.UrlWithClicksCount:
    properties:
      clicks_count:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      long_url:
        type: string
      short_code:
        type: string
      updated_at:
        type: string
    type: object
  request.CreateUrl:
    properties:
      long_url:
        maxLength: 2048
        type: string
    required:
    - long_url
    type: object
  response.Fail:
    properties:
      error:
        type: string
      errors:
        items:
          type: string
        type: array
    type: object
  response.List:
    properties:
      data: {}
      pagination:
        $ref: '#/definitions/dto.Pagination'
    type: object
  response.Ok:
    properties:
      data: {}
    type: object
info:
  contact: {}
  title: url shortener api
  version: "1.0"
paths:
  /{short_code}:
    get:
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: click short code
      tags:
      - url
  /urls:
    post:
      consumes:
      - application/json
      parameters:
      - description: create url
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.CreateUrl'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.Ok'
            - properties:
                data:
                  $ref: '#/definitions/model.Url'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: create url
      tags:
      - url
  /urls/{short_code}:
    get:
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Ok'
            - properties:
                data:
                  $ref: '#/definitions/model.UrlWithClicksCount'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: url stats
      tags:
      - url
  /urls/{short_code}/clicks:
    get:
      consumes:
      - application/json
      parameters:
      - description: short code
        in: path
        name: short_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.List'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Click'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Fail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Fail'
      summary: get clicks by url
      tags:
      - click
swagger: "2.0"
